# Generated by Django 6.0.4 on 2026-04-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("anchor_class", models.CharField(max_length=10)),
                ("icon_class", models.CharField(max_length=30)),
                ("url", models.CharField(max_length=200)),
            ],
        ),
    ]
