# Generated by Django 6.0.4 on 2026-04-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_advertisement_celebrity_movietheater_movietv_news_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='movie_genre',
            field=models.CharField(max_length=50),
        ),
    ]
